### ISSUE TITLE
Allow updating Zed and extensions from the CLI

### ISSUE THREAD

**Issue by GideonBear** [GideonBear/zed#1]
### Check for existing issues

- [X] Completed

### Describe the feature

Add an option (`zed --update`) to the CLI that updates Zed and its extensions headlessly (without loading and opening the GUI).
Obviously updating Zed itself would only make sense if it is installed by itself and not via a package manager; if it would update itself normally.

I don't mind Zed updating automatically at startup, but having to restart it is wasting time; if I could incorporate updating Zed into my daily update command (or into [topgrade](https://github.com/topgrade-rs/topgrade)), I would not have to update it at the time I want to use it, and can instead do it at the time I am doing all other updates.

### Todo:
- [ ] Test that it works
- [ ] Test how auto-upgrading works in [non-standalone distributions](https://zed.dev/docs/linux#other-ways-to-install-zed-on-linux)
  - [ ] Make sure it does the same
  - [ ] Test that, and that it still updates extensions
- [ ] Make & merge PR
- [ ] Integrate into topgrade

**Comment by GideonBear** [comment]
Patch for now

```diff
diff --git a/crates/cli/src/main.rs b/crates/cli/src/main.rs
index 002b0c0173..04f1e1f8b0 100644
--- a/crates/cli/src/main.rs
+++ b/crates/cli/src/main.rs
@@ -59,6 +59,9 @@ struct Args {
     /// Run zed in dev-server mode
     #[arg(long)]
     dev_server_token: Option<String>,
+    /// Update zed and its extensions
+    #[arg(long)]
+    update: bool,
 }
 
 fn parse_path_with_position(argument_str: &str) -> anyhow::Result<String> {
@@ -119,6 +122,11 @@ fn main() -> Result<()> {
         return Ok(());
     }
 
+    if args.update {
+        println!("We updatin");
+        return Ok(());
+    }
+
     let (server, server_name) =
         IpcOneShotServer::<IpcHandshake>::new().context("Handshake before Zed spawn")?;
     let url = format!("zed-cli://{server_name}");
```
